name: 'Slack Reporter'
description: 'Send messages to Slack channels with thread support and reactions'
author: 'nsingla'

inputs:
  slack-bot-token:
    description: 'Slack Bot Token (starts with xoxb-)'
    required: true
  channel-name:
    description: 'Slack channel name (without #)'
    required: true
  message:
    description: 'Message to send to Slack'
    required: true
  thread-ts:
    description: 'Parent message timestamp for threading (optional)'
    required: false
    default: ''
  add-reaction:
    description: 'Add reaction to the message (true/false)'
    required: false
    default: 'false'
  reaction-emoji:
    description: 'Emoji name for reaction (default: white_check_mark)'
    required: false
    default: 'white_check_mark'

outputs:
  message-ts:
    description: 'Timestamp of the sent message'
  channel-id:
    description: 'ID of the channel where message was sent'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install slack-sdk==3.37.0

    - name: Run Slack Reporter
      shell: bash
      run: python ${{ github.action_path }}/run_action.py
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_NAME: ${{ inputs.channel-name }}
        SLACK_MESSAGE: ${{ inputs.message }}
        PARENT_SLACK_MESSAGE_TIMESTAMP: ${{ inputs.thread-ts }}
        ADD_REACTION: ${{ inputs.add-reaction }}
        REACTION_EMOJI: ${{ inputs.reaction-emoji }}

branding:
  icon: 'message-circle'
  color: 'blue'